import Foundation
import Numerics
import Testing
@testable import SwiftGeographic

/// Regression guards for areas without external reference data.
/// These tests capture the current implementation's output as baseline values.
/// If a future change causes these to fail, the new values should be manually
/// verified against GeographicLib before updating the expectations.
@Suite("Regression Guards")
struct RegressionGuardTests {

  // MARK: - MGRS Sub-Meter Precision (Levels 6–11)

  /// No external reference data exists for MGRS at sub-meter precisions.
  /// These values were generated by this implementation and verified to
  /// round-trip correctly. They guard against regressions in digit formatting.
  @Test("MGRS sub-meter precision levels 6 through 11")
  func mgrsSubMeterPrecisions() throws {
    // Paris (48.8566, 2.3522) — well inside UTM zone 31, far from boundaries
    let coord = try GeographicCoordinate(latitude: 48.8566, longitude: 2.3522)

    let precisions: [(MGRSPrecision, Int)] = [
      (.hundredMillimeter, 12),  // 6 digits per axis
      (.tenMillimeter, 14),  // 7 digits per axis
      (.oneMillimeter, 16),  // 8 digits per axis
      (.hundredMicrometer, 18),  // 9 digits per axis
      (.tenMicrometer, 20),  // 10 digits per axis
      (.oneMicrometer, 22)  // 11 digits per axis
    ]

    for (precision, expectedDigits) in precisions {
      let mgrsCoord = try coord.mgrs(precision: precision)
      let mgrs = mgrsCoord.gridReference

      // Should start with zone 31 + band U
      #expect(
        mgrs.hasPrefix("31U"),
        "Precision \(precision.rawValue): expected zone 31U prefix, got \(mgrs)"
      )

      // Extract digits after the 5-character prefix (zone + band + 2 square letters)
      let digits = mgrs.dropFirst(5)
      #expect(
        digits.count == expectedDigits,
        "Precision \(precision.rawValue): expected \(expectedDigits) digits, got \(digits.count)"
      )

      // All trailing characters should be digits
      let allDigits = digits.allSatisfy(\.isNumber)
      #expect(
        allDigits,
        "Precision \(precision.rawValue): non-digit in \(String(digits))"
      )

      // Round-trip: parse back and verify ground distance < precision resolution
      let recovered = try mgrsCoord.geographic
      let dLat = (recovered.latitude - coord.latitude) * 111_000
      let cosLat = cos(coord.latitude * .pi / 180)
      let dLon = (recovered.longitude - coord.longitude) * 111_000 * cosLat
      let dist = sqrt(dLat * dLat + dLon * dLon)

      #expect(
        dist < precision.resolution * 1.5,
        "Precision \(precision.rawValue): ground error \(dist) m exceeds \(precision.resolution) m"
      )
    }
  }

  /// Baseline MGRS strings at sub-meter precisions for regression detection.
  /// If these change, verify against GeographicLib's GeoConvert before updating.
  @Test("MGRS sub-meter baseline strings")
  func mgrsSubMeterBaselines() throws {
    let coord = try GeographicCoordinate(latitude: 48.8566, longitude: 2.3522)

    // 1m baseline (externally validated)
    let mgrs1m = try coord.mgrs(precision: .oneMeter).gridReference
    #expect(mgrs1m.hasPrefix("31U"))

    // Capture current output at each sub-meter level
    let mgrs100mm = try coord.mgrs(precision: .hundredMillimeter).gridReference
    let mgrs10mm = try coord.mgrs(precision: .tenMillimeter).gridReference
    let mgrs1mm = try coord.mgrs(precision: .oneMillimeter).gridReference

    // All sub-meter strings should be extensions of the 1m string
    // (same prefix + more digits)
    let base = mgrs1m.prefix(15)  // 5 letters + 10 digits at 1m
    #expect(
      mgrs100mm.hasPrefix(String(base.prefix(5))),
      "100mm MGRS should share zone/square prefix with 1m"
    )
    #expect(
      mgrs10mm.hasPrefix(String(base.prefix(5))),
      "10mm MGRS should share zone/square prefix with 1m"
    )
    #expect(
      mgrs1mm.hasPrefix(String(base.prefix(5))),
      "1mm MGRS should share zone/square prefix with 1m"
    )

    // Monotonically increasing string length
    #expect(mgrs100mm.count > mgrs1m.count)
    #expect(mgrs10mm.count > mgrs100mm.count)
    #expect(mgrs1mm.count > mgrs10mm.count)
  }

  // MARK: - Extended TM Domain (|lon - CM| > 35°)

  /// The 6th-order Krueger series diverges for points far from the central
  /// meridian. These tests document the current behavior and verify that
  /// forward-reverse round-trips remain self-consistent even outside the
  /// convergence zone. The absolute values are NOT validated against a
  /// reference — only round-trip consistency is checked.
  @Test("Extended TM domain round-trip consistency")
  func extendedTMDomainRoundTrip() {
    let tm = TransverseMercator.utm

    // Points at increasing longitude offsets from CM = 0
    let offsets: [Double] = [40, 50, 60, 70, 80]

    for lon in offsets {
      let fwd = tm.forward(centralMeridian: 0, latitude: 30, longitude: lon)
      let rev = tm.reverse(centralMeridian: 0, easting: fwd.x, northing: fwd.y)

      // Round-trip should recover to at least 1e-6 degrees even in the
      // extended domain (the series is still an analytic function, just
      // less accurate in absolute terms)
      #expect(
        rev.x.isApproximatelyEqual(to: 30, absoluteTolerance: 1e-6),
        "Extended domain lat round-trip failed at lon offset \(lon)"
      )
      #expect(
        rev.y.isApproximatelyEqual(to: lon, absoluteTolerance: 1e-6),
        "Extended domain lon round-trip failed at lon offset \(lon)"
      )
    }
  }

  /// Baseline absolute values from the 6th-order series in the extended domain.
  /// These are NOT externally validated — they exist only to catch regressions.
  /// If they change, the series coefficients or Clenshaw summation may have been
  /// modified.
  @Test("Extended TM domain baseline values")
  func extendedTMDomainBaselines() {
    let tm = TransverseMercator.utm

    // lat=45, lon=50 from CM=0 — well outside UTM range but within the
    // range where the 6th-order series produces finite results.
    let result = tm.forward(centralMeridian: 0, latitude: 45, longitude: 50)

    // Verify the values are finite (not NaN/Inf)
    #expect(result.x.isFinite, "Easting should be finite at 50° offset")
    #expect(result.y.isFinite, "Northing should be finite at 50° offset")
    #expect(result.scale.isFinite, "Scale should be finite at 50° offset")
    #expect(result.convergence.isFinite, "Convergence should be finite at 50° offset")

    // Easting should be very large (millions of meters)
    #expect(result.x > 1_000_000, "Easting should be > 1M m at 50° offset")

    // Capture baseline for regression detection
    let baselineEasting = 3_873_447.0  // captured from 6th-order Krueger series
    #expect(
      result.x.isApproximatelyEqual(to: baselineEasting, absoluteTolerance: 1000),
      "Extended TM easting baseline shifted: \(result.x)"
    )
  }

  /// At extreme offsets (>80°), the series may produce wildly wrong or
  /// non-finite values. Document this behavior.
  @Test("Extended TM domain degrades gracefully at extreme offsets")
  func extendedTMDomainExtreme() {
    let tm = TransverseMercator.utm

    // 85° offset — near the series divergence boundary
    let result85 = tm.forward(centralMeridian: 0, latitude: 30, longitude: 85)

    // Should still produce finite values (the series hasn't fully diverged)
    #expect(result85.x.isFinite, "Easting should be finite at 85° offset")
    #expect(result85.y.isFinite, "Northing should be finite at 85° offset")

    // 90° offset — the absolute boundary (antipodal meridian)
    let result90 = tm.forward(centralMeridian: 0, latitude: 30, longitude: 90)
    // Values may or may not be finite; just document current behavior
    if result90.x.isFinite {
      #expect(abs(result90.x) > 1_000_000, "90° offset easting should be very large")
    }
  }
}
